### ISSUE TITLE
NiTE: HandViewer failed assertion in malloc.c

### ISSUE THREAD

**Issue by piedar** [OpenNI/OpenNI2#27]
The NiTE 2.2 sample HandViewer aborts with a failed assertion in malloc.c on Linux 3.8.13 with gcc 4.6.3.

```
HandViewer: malloc.c:2451: sYSMALLOc: Assertion `(old_top == (((mbinptr) (((char *) &((av)->bins[((1) - 1) * 2])) - __builtin_offsetof (struct malloc_chunk, fd)))) && old_size == 0) || ((unsigned long) (old_size) >= (unsigned long)((((__builtin_offsetof (struct malloc_chunk, fd_nextsize))+((2 * (sizeof(size_t))) - 1)) & ~((2 * (sizeof(size_t))) - 1))) && ((old_top)->size & 0x1) && ((unsigned long)old_end & pagemask) == 0)' failed.

Program received signal SIGABRT, Aborted.
0x000000389aa37c15 in raise () from /lib64/libc.so.6
(gdb) backtrace
#0  0x000000389aa37c15 in raise () from /lib64/libc.so.6
#1  0x000000389aa3908b in abort () from /lib64/libc.so.6
#2  0x000000389aa7cb2d in ?? () from /lib64/libc.so.6
#3  0x000000389aa7f8eb in ?? () from /lib64/libc.so.6
#4  0x000000389aa81545 in malloc () from /lib64/libc.so.6
#5  0x000000389c2bc13d in operator new(unsigned long) () from /usr/lib/gcc/x86_64-pc-linux-gnu/4.6.3/libstdc++.so.6
#6  0x00007ffff781da78 in NHAGestureRecognizerManager::Initialize(NACommonData*, xn::DepthGenerator const&, xn::DepthMetaData const&, std::string const&, int, int) ()
   from ./libNiTE2.so
#7  0x00007ffff7497663 in HandTracker::initializeTracker() () from ./libNiTE2.so
#8  0x00007ffff749860e in niteInitializeHandTrackerByDevice () from ./libNiTE2.so
#9  0x00000000004024f0 in SampleViewer::Init(int, char**) ()
#10 0x00000000004020ed in main ()
```

**Comment by ddway2** [comment]
I have the same problem, the issue https://github.com/piedar/OpenNI2-FreenectDriver/issues/22 cannot resolve it
