### ISSUE TITLE
Building Documentation with Java 8 fails

### ISSUE THREAD

**Issue by christian-sahlmann** [OpenNI/OpenNI2#87]
```
% python Source/Documentation/Runme.py
Traceback (most recent call last):
  File "Source/Documentation/Runme.py", line 50, in <module>
    subprocess.check_call(cmd, stdout=open(os.devnull,"w"), stderr=open(errfile,"w"))
  File "/usr/lib/python3.4/subprocess.py", line 561, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['javadoc', '-d', 'java', '../../Wrappers/java/OpenNI.java/src/org/openni/VideoStream.java', '../../Wrappers/java/OpenNI.java/src/org/openni/VideoMode.java', '../../Wrappers/java/OpenNI.java/src/org/openni/VideoFrameRef.java', '../../Wrappers/java/OpenNI.java/src/org/openni/Version.java', '../../Wrappers/java/OpenNI.java/src/org/openni/SensorType.java', '../../Wrappers/java/OpenNI.java/src/org/openni/SensorInfo.java', '../../Wrappers/java/OpenNI.java/src/org/openni/Recorder.java', '../../Wrappers/java/OpenNI.java/src/org/openni/Point3D.java', '../../Wrappers/java/OpenNI.java/src/org/openni/Point2D.java', '../../Wrappers/java/OpenNI.java/src/org/openni/PlaybackControl.java', '../../Wrappers/java/OpenNI.java/src/org/openni/PixelFormat.java', '../../Wrappers/java/OpenNI.java/src/org/openni/OutArg.java', '../../Wrappers/java/OpenNI.java/src/org/openni/OpenNI.java', '../../Wrappers/java/OpenNI.java/src/org/openni/NativeMethods.java', '../../Wrappers/java/OpenNI.java/src/org/openni/ImageRegistrationMode.java', '../../Wrappers/java/OpenNI.java/src/org/openni/DeviceInfo.java', '../../Wrappers/java/OpenNI.java/src/org/openni/Device.java', '../../Wrappers/java/OpenNI.java/src/org/openni/CropArea.java', '../../Wrappers/java/OpenNI.java/src/org/openni/CoordinateConverter.java']' returned non-zero exit status 1
```

```
% cat Source/Documentation/Temp/javadoc_error
../../Wrappers/java/OpenNI.java/src/org/openni/CoordinateConverter.java:57: error: unknown tag: Integer
   * @return Point3D<Integer> Coordinate of the output value, and depth measured in the
                    ^
../../Wrappers/java/OpenNI.java/src/org/openni/CoordinateConverter.java:88: error: unknown tag: t
   *         <t> the Y coordinate of the output value, measured in pixels with 0.0 at the top of the
             ^
../../Wrappers/java/OpenNI.java/src/org/openni/CoordinateConverter.java:91: error: unknown tag: t
   *         <t> the Z(depth) coordinate of the output value, measured in millimeters with 0.0 at
             ^
../../Wrappers/java/OpenNI.java/src/org/openni/CoordinateConverter.java:118: error: unknown tag: Float
   * @return Point3D<Float> to a place to store the X,Y,Z coordinate of the output value, measured
                    ^
../../Wrappers/java/OpenNI.java/src/org/openni/CoordinateConverter.java:146: error: unknown tag: Float
   * @return Point3D<Float> to a place to store the X coordinate of the output value, measured in
                    ^
../../Wrappers/java/OpenNI.java/src/org/openni/Device.java:48: warning: no @return
  public static Device open(String uri) {
                       ^
../../Wrappers/java/OpenNI.java/src/org/openni/Device.java:65: warning: no @return
  public static Device open() {
                       ^
../../Wrappers/java/OpenNI.java/src/org/openni/Device.java:151: warning: no @param for mode
  public boolean isImageRegistrationModeSupported(ImageRegistrationMode mode) {
                 ^
../../Wrappers/java/OpenNI.java/src/org/openni/OpenNI.java:170: warning: no @throws for java.util.concurrent.TimeoutException
  public static int waitForAnyStream(List<VideoStream> streams, int timeout) throws TimeoutException {
                    ^
../../Wrappers/java/OpenNI.java/src/org/openni/OpenNI.java:53: warning: no @param for info
    void onDeviceConnected(DeviceInfo info);
         ^
../../Wrappers/java/OpenNI.java/src/org/openni/OpenNI.java:82: warning: no @param for info
    void onDeviceDisconnected(DeviceInfo info);
         ^
../../Wrappers/java/OpenNI.java/src/org/openni/OpenNI.java:105: warning: no @param for info
    void onDeviceStateChanged(DeviceInfo info, int deviceState);
         ^
../../Wrappers/java/OpenNI.java/src/org/openni/OpenNI.java:105: warning: no @param for deviceState
    void onDeviceStateChanged(DeviceInfo info, int deviceState);
         ^
../../Wrappers/java/OpenNI.java/src/org/openni/PlaybackControl.java:40: warning: no @return
  public float getSpeed() {
               ^
../../Wrappers/java/OpenNI.java/src/org/openni/Recorder.java:29: warning: no @return
  public static Recorder create(String fileName) {
                         ^
../../Wrappers/java/OpenNI.java/src/org/openni/VideoFrameRef.java:106: warning: no @return
  public int getHeight() {
             ^
../../Wrappers/java/OpenNI.java/src/org/openni/VideoStream.java:112: warning: no @return
  public static VideoStream create(Device device, SensorType sensorType) {
                            ^
../../Wrappers/java/OpenNI.java/src/org/openni/VideoStream.java:100: warning: no @param for stream
    public void onFrameReady(VideoStream stream);
                ^
```
# Workaround

in Runme.py, replace

> cmd = [javaDocExe, '-d', 'java']

with

> cmd = [javaDocExe, '-d', 'java', '-Xdoclint:none']

**Comment by Algomorph** [comment]
Thanks for the work-around.
